# spring.datasource.url=jdbc:mysql://mysql-project-calculator-db-server.mysql.database.azure.com/projectdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Use environment variables in edit configuration to set PROD_DATABASE_URL, PROD_USERNAME and PROD_PASSWORD
spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASSWORD}

# false to stop application startup if there are errors in the SQL scripts
spring.sql.init.continue-on-error=false

# always to initialize the database schema and data on startup
# spring.sql.init.mode=never
spring.sql.init.mode=always
#================================================================
# Database name: projectdb
# name to fit in your MySQL server before running the application

#================================================================
